puts "Hi I am joining Runchise today"
puts "What color do you like wearing today?"
puts "If you wear green you will be like a mud in a garden."
#puts "If you wear red then you will be very attractive to people around you"
#puts "If you wear black you will emit a gloomy or not-to-positive aura"
puts "So what color will you be using today?"